apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend
          image: munisekar/frontend-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_USER_SERVICE_URL
              value: "http://localhost:3001"
            - name: REACT_APP_PRODUCT_SERVICE_URL
              value: "http://localhost:3002"
            - name: REACT_APP_CART_SERVICE_URL
              value: "http://localhost:3003"
            - name: REACT_APP_ORDER_SERVICE_URL
              value: "http://localhost:3004"

