apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user
          image: munisekar/user-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://munisheak:r2V7267uMR1qUvRt@munish-travel-mem.sz1p7kc.mongodb.net/ecommerce_users"
         
           envFrom:
             - configMapRef:
               name: user-service
